-- =============================================================================
-- Stock Advisors - SQLite Database Schema
-- =============================================================================
-- Core tables for paper trading, agent track records, analysis archiving,
-- and performance reviews. Designed for SQLite via @tauri-apps/plugin-sql.
-- =============================================================================

-- -----------------------------------------------------------------------------
-- Paper Trades
-- -----------------------------------------------------------------------------
-- Every paper trade executed by the system. Tracks entry, exit, P&L, and
-- which agent recommended the position.

CREATE TABLE IF NOT EXISTS trades (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  symbol TEXT NOT NULL,
  action TEXT NOT NULL,
  quantity INTEGER NOT NULL,
  entry_price REAL NOT NULL,
  entry_date TEXT NOT NULL,
  exit_price REAL,
  exit_date TEXT,
  stop_loss REAL,
  take_profit REAL,
  status TEXT DEFAULT 'open',
  pnl_dollars REAL,
  pnl_percent REAL,
  holding_days INTEGER,
  recommended_by TEXT NOT NULL,
  confidence INTEGER,
  pipeline_id TEXT,
  notes TEXT,
  created_at TEXT DEFAULT (datetime('now'))
);

-- -----------------------------------------------------------------------------
-- Agent Track Records
-- -----------------------------------------------------------------------------
-- Every recommendation made by an agent, whether acted upon or not.
-- Tracks the predicted outcome vs. what actually happened.

CREATE TABLE IF NOT EXISTS agent_track_records (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  agent_id TEXT NOT NULL,
  symbol TEXT NOT NULL,
  recommendation TEXT NOT NULL,
  confidence INTEGER,
  target_price REAL,
  stop_loss REAL,
  recommended_at TEXT NOT NULL,
  outcome TEXT,
  actual_return REAL,
  peak_return REAL,
  worst_drawdown REAL,
  days_to_outcome INTEGER,
  resolved_at TEXT,
  created_at TEXT DEFAULT (datetime('now'))
);

-- -----------------------------------------------------------------------------
-- Analysis Snapshots
-- -----------------------------------------------------------------------------
-- Full input/output archives of every agent run. Used for debugging,
-- back-testing, and injecting historical context into future prompts.

CREATE TABLE IF NOT EXISTS analysis_snapshots (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  pipeline_id TEXT,
  agent_id TEXT NOT NULL,
  symbols TEXT NOT NULL,
  input_data TEXT NOT NULL,
  output_data TEXT NOT NULL,
  summary TEXT,
  confidence INTEGER,
  token_usage TEXT,
  created_at TEXT DEFAULT (datetime('now'))
);

-- -----------------------------------------------------------------------------
-- Performance Reviews
-- -----------------------------------------------------------------------------
-- Periodic performance assessments generated by the Performance Analyst agent.
-- Stored for trend analysis and continuous improvement.

CREATE TABLE IF NOT EXISTS performance_reviews (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  review_type TEXT NOT NULL,
  agent_id TEXT,
  period_start TEXT NOT NULL,
  period_end TEXT NOT NULL,
  findings TEXT NOT NULL,
  recommendations TEXT NOT NULL,
  created_at TEXT DEFAULT (datetime('now'))
);

-- -----------------------------------------------------------------------------
-- Indexes
-- -----------------------------------------------------------------------------

CREATE INDEX IF NOT EXISTS idx_trades_symbol ON trades(symbol);
CREATE INDEX IF NOT EXISTS idx_trades_status ON trades(status);
CREATE INDEX IF NOT EXISTS idx_trades_recommended_by ON trades(recommended_by);
CREATE INDEX IF NOT EXISTS idx_track_agent ON agent_track_records(agent_id);
CREATE INDEX IF NOT EXISTS idx_track_symbol ON agent_track_records(symbol);
CREATE INDEX IF NOT EXISTS idx_snapshots_pipeline ON analysis_snapshots(pipeline_id);
CREATE INDEX IF NOT EXISTS idx_snapshots_agent ON analysis_snapshots(agent_id);
